### ISSUE TITLE
Vim is crashed if input() was called with complete functions

### ISSUE THREAD

**Issue by sgur** [h-east/vim#20]
input() 関数を第3引数つき(補完つき)で呼び出すと、補完を開始したタイミングで落ちます。
### Environment
- Windows 10 64bit
- MINGW64 でビルド
### How to reproduce

``` sh
gvim -N -u NONE または vim -N -u NONE
```

で起動した後、
以下のスクリプトを読み込みます(cmdlineから入力しても再現可能)

``` vim
set wildmenu wildmode=popup
call input('', '', 'option')
```

`<TAB>` を何度か叩きます。

**Comment by sgur** [comment]
同じ現象をインサートモードで発生することも確認しましたので、追記しておきます。

``` vim
<C-\><C-n>i<C-r>=input('', '', 'option')<CR><TAB><TAB>...
```

でも同様でした。
ご参考までに。

**Comment by h-east** [comment]
@sgur issue登録ありがとうございます。

SEGVしないように修正しました。
あと以下の現象を直さなければなりません。(いずれも`input()`経由でCLPUM発動させた時のみの挙動です)
- 最終行の表示(`-- Command-line mode completion (^N^P) match 1 of 365`みたいなやつ)が表示されない。
- 補完item数が変化した時に直前のpopup menuの表示が残っている。

**Comment by sgur** [comment]
ありがとうございます。 SEGVしないことは確認しました。

ところで、確認の過程で見つけたのですが、端末版のVim の場合、https://github.com/h-east/vim/issues/20#issuecomment-229547875 の手順を実施した場合に、`<TAB>`の入力で画面全体が更新され、端末内が消えて(クリア)されてしまうように思えます。もしかしたら Windows の端末版のみかもしれません。
ご確認頂けますでしょうか。

**Comment by h-east** [comment]
@sgur Windows の端末版(MinGW32ビルド)で現象を確認しました。うわぁ、スゴいチラツキですね:grimacing:
Linux CUI版では起きていないようです。
こちらも合わせて調査します。

**Comment by h-east** [comment]
Windows の端末版(MinGW32ビルド)でいろいろCLPUM動かしてみたら明らかに挙動がLinux CUI版と違う。。
なんだこりゃー！

**Comment by h-east** [comment]
@sgur 遅くなりましたが、以下の現象を修正しました。

> - 最終行の表示(`-- Command-line mode completion (^N^P) match 1 of 365`みたいなやつ)が表示されない。
> - 補完item数が変化した時に直前のpopup menuの表示が残っている。

Windows版CUIのチラツキもなくなったと思います。確認をお願いします。

**Comment by sgur** [comment]
修正ありがとうございます。

手元で確認してみた限り、GUI, CUI 版ともに問題なく動作しているようです。

**Comment by h-east** [comment]
@sgur Thanks for the confirming this :+1:
