### ISSUE TITLE
The first item is not inserted to command-line

### ISSUE THREAD

**Issue by tyru** [h-east/vim#23]
# Problem

The first item `bar` is selected in completion menu, but not inserted to command-line
when pressing `<Tab>` to complete file paths.

![820374ec9ac22beedc04a531637fc0c5](https://user-images.githubusercontent.com/48169/48476785-4f8e9f80-e843-11e8-80f0-8b1e35a9d733.gif)

# Steps to reproduce

```vim
set wildmode=popup
set wildmenu
set clpumheight=40
```

```
$ ls -1 tmp
bar
baz
foo
```

1. `vim --clean -S clpum.vim`
1. `:e tmp/<Tab>`

It shows `bar`, `baz`, `foo` in completion menu, and the first item `bar` is selected.
But `bar` is not inserted to command-line.
So the next `<Tab>` selects and inserts the second item `baz` not the first item `bar`.

**Comment by h-east** [comment]
The pointed out behavior is the same in Insert mode.

```bash
$ vim --clean +"set cot+=noinsert"
```
Start Insert-mode and type `tmp/` then type file name completion (`<C-X><C-F>`).
```vim
itmp/<C-X><C-F>
```

Thanks for reporting this:+1:

**Comment by tyru** [comment]
Thanks for reply 😄
Hmm, is it possible to get `set cot-=noinsert` behavior when pressing `<Tab>`?

**Comment by h-east** [comment]
Yes.
```
set clcot-=noinsert
```
Sorry I did not have a document.  I am glad if you guess from the following list.
http://h-east.github.io/vim/#addedchanged-options-event-and-etc

**Comment by tyru** [comment]
Sorry, I missed that option! It works now.
Thanks 😄

**Comment by h-east** [comment]
Ah, I wrote a part of document 😅 
Please execute this.
```
:helptags (your vim-clpum runtime path)/doc
```

I will update the helptags of the repository.
