### ISSUE TITLE
Shift-Tab does not show popup

### ISSUE THREAD

**Issue by tyru** [h-east/vim#24]
# Problem

With `vim --clean`, Shift-Tab in command-line completes the last filename.
I want clpum to show popup even when pressing Shift-Tab.

![502aebc532f9f3182cda6fa98806e370](https://user-images.githubusercontent.com/48169/48553970-78389700-e920-11e8-923f-a25364c880b5.gif)

Sorry, I tried this only in CUI Vim.

# Steps to reproduce

vimrc

```vim
set wildmode=popup
set wildmenu
set clpumheight=40
```

1. `vim --clean -S clpum.vim`
1. `:e <S-Tab>`

It does not show popup.
It works the same as plain vim behavior.

# Environment

WSL Debian 9.5
Microsoft Windows 10 Pro 64bit 10.0.17134

**Comment by h-east** [comment]
@tyru Patch updated.
Please confirm the issue cleared.

**Comment by tyru** [comment]
Confirmed!
Thanks for quick fix! 😄
